name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run action
      uses: frankie567/setup-sqlite-action@main
    - name: Check SQLite version
      shell: bash
      run: |
        echo "$PATH"
        which sqlite3
        sqlite3 --version
